from typing import Optional


class Message():
    """
    Message is the data packet format in the system.
    Attributes:
        EOF (bool): identifier to determine whether a message is valid or not
        task (str): Description of the task.
        agent_id (uuid.UUID): Unique identifier for the agent. 
        agent_role (str): Role for the agent.
        id: Unique identifier for the operation in a agent.
        textual_output: The text output by an operation of an agent.

    Agent or operation receive (raw_inputs, messages, self_messages)-> (outputs)
        raw_inputs (Message): all information of a task received from the user
        messages (List[Message]): the messages/outputs received from the neighbors 
        self_messages (List[Message]): the
        outputs (List[Message]): the outputs generated by an operation
    """
    def __init__(self, EOF: bool = False,
                 agent_id: Optional[str] = None, 
                 agent_role: Optional[str] = None,
                 id: Optional[str] = None,
                 task: Optional[str] = None,
                 textual_output: Optional[str] = None):
        self.EOF = EOF
        self.agent_id = agent_id
        self.agent_role = agent_role
        self.id = id
        self.task = task
        self.textual_output = textual_output
                
    def message2text(self, message_id: int):       # You can add message_id as an attribute, but I guess [0,1,2,3,..] is more clear.
        agent_id = self.agent_id if self.agent_id else "None"
        agent_role = self.agent_role if self.agent_role else "None"
        textual_output = self.textual_output if self.textual_output else "None"
        
        textual_message = ""
        textual_message = textual_message + "message" + "{\n"
        textual_message = textual_message + "meesage id: " + str(message_id) + ";\n"
        textual_message = textual_message + "expert id: " + agent_id + ";\n"
        textual_message = textual_message + "role: " + agent_role + ";\n"
        if self.EOF:
            textual_message = textual_message + "thoughts: " + "EOF." + "\n}\n"
        else:
            textual_message = textual_message + "thoughts: " + textual_output + "\n}\n"
        return textual_message

    def message2print(self):
        agent_id = self.agent_id if self.agent_id else "None"
        agent_role = self.agent_role if self.agent_role else "None"
        textual_output = self.textual_output if self.textual_output else "None"
        
        textual_message = ""
        textual_message = textual_message + "message" + "{\n"
        textual_message = textual_message + "Agent id: " + agent_id + ";\n"
        textual_message = textual_message + "role: " + agent_role + ";\n"
        if self.EOF:
            textual_message = textual_message + "thoughts: " + "EOF." + "\n}\n"
        else:
            textual_message = textual_message + "thoughts: " + textual_output + "\n}\n"
        return textual_message
        